export const userTable = 'table';
export const linhaTableTr = 'table tbody tr';
export const colunaTableTh = 'table th';
export const novoUsuarioBtn = 'button#new-user';
export const modalContent = 'div.react-modal-content';
export const closeModal = 'button.react-modal-close';
export const editUserBtn = 'table>tbody>tr>td>button>img[alt="edit"]';
export const deleteUserBtn = 'table>tbody>tr>td>button>img[alt="delete"]';
export const sweetAlert = 'div.swal2-modal';
export const sweetAlertConfirm = 'button.swal2-confirm';
